### ISSUE TITLE
Parse .gitignore to ignore more files

### ISSUE THREAD

**Issue by sparr** [Pandemoneus/Biter-Spire#2]
`shutil.copytree('.', modDir, ignore=shutil.ignore_patterns('*.py', '.git'))`

if .git and .gitignore exist, it would be great if .gitignore was parsed to ignore additional files (like *.pyc, ~*, etc)

**Comment by Pandemoneus** [comment]
Hi, just pushed a commit that should do what you suggested:
https://github.com/Pandemoneus/Biter-Spire/commit/7754380fd9b8379437081a0257286c866c2d3f4f

If this is not what you had in mind, open this issue again. :)

**Comment by sparr** [comment]
Looks awesome! Thanks.
